# Generated by Django 2.0 on 2018-09-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spam_gator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockedEmail',
            new_name='BlockedEmails',
        ),
    ]
