# Generated by Django 2.0 on 2018-10-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_gator', '0002_auto_20180919_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
