# Generated by Django 2.0 on 2018-10-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spam_gator', '0003_blockedips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockedIps',
            new_name='BlockedIp',
        ),
    ]
