# Generated by Django 2.0 on 2019-01-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spam_gator', '0005_blockedword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockedEmails',
            new_name='BlockedEmail',
        ),
    ]
